### ISSUE TITLE
JSONLinesLint?

### ISSUE THREAD

**Issue by GrahamHannington** [circlecell/jsoncompare.com#1]
Thank you for JSONLint.

I'd like a variant, or perhaps an option added to JSONLint, that validates [JSON Lines](http://jsonlines.org/).

That is, I want to paste in multiple lines of JSON Lines, and have JSONLint validate each line as a separate JSON object.

I understand at least some of the repercussions of what I'm asking for. For example, reformatting: inserting line breaks in JSON = pretty; inserting line breaks in JSON Lines = _pretty ugly_ :smile:.

**Comment by GrahamHannington** [comment]
Oops. Did I create an issue for the wrong project? Should I have added this to circlecell/jsonlintdotcom instead?

**Comment by finom** [comment]
This is the good place to make such feature requests because we're not going to add any new features to jsonlintdotcom.

How are you going to fill the field?  Are you going to manually copy-paste or use curl to pass JSON as a parameter?

**Comment by GrahamHannington** [comment]
> Are you going to manually copy-paste or use curl to pass JSON as a parameter?

Initally, just the former. Later, if I understand you correctly (my ignorance laid bare below :smile:), it would be nice to be able to pass literal JSON Lines (with the end-of-line markers percent-encoded), or the URL of a file containing JSON Lines, in the query string of the JSONLint URL.

So far, I have only been manually copying'n'pasting relatively small ad hoc JSON objects (or arrays) into (a locally hosted copy of) the [pure JavaScript version of JSONLint](https://github.com/zaach/jsonlint) (jsonlint.html) by Zachary Carter. (So - again, with apologies; I don't mean to waste your time - maybe I should be asking Zachary?) I haven't even tried the CLI yet. Not exactly a power user, right? However, being able to validate JSON Lines would mean that I'd throw more at JSONLint at one time, which means I'd likely ditch manual copying'n'pasting.

I use curl routinely in other contexts, but it's not occurred to me to use curl with JSONLint. I realize I might be misunderstanding you here, but not maliciously: I know I can pass a URL via the json parameter of the query string; is that what you mean (and that feature is implemented via curl)? Or are you referring to something else?

**Comment by finom** [comment]
test.jsonlint.com is a demo of the new online JSON linter which is going to have all needed features required by the community (it closes most of feature requests for jsonlint.com). Potentially, the feature you propose can be added somehow to the project (I hope it will be launched soon). I'm just thinking about how to add your feature and don't break existing stuff and how much this feature is needed.

I'm thinking about to create CLI tool which will have something like  ``--jsonlines=foo.jsonl`` flag and when you run it it will fill "Batch" tab (curl + small manipulations is one of the ways to make it right now without extra tools) with foo.jsonl contents and open a browser ... Don't know does it make sense.

**Comment by finom** [comment]
Closing because we're  not interested to add this feature. Thank you.
