### ISSUE TITLE
Support JSON Schema

### ISSUE THREAD

**Issue by alexdresko** [circlecell/jsoncompare.com#10]
Just tossing this idea out there. Saw [this article](https://visualstudiomagazine.com/articles/2018/02/21/supporting-devs-json-schema.aspx) today and also had to use jsoncompare.com. 

I haven't put much additional thought into the idea but figured it's worth a discussion.

**Comment by finom** [comment]
I think that such a feature needs to be done behind another app, not as a part of JSONCompare.
