### ISSUE TITLE
limitation on merging

### ISSUE THREAD

**Issue by Wtango** [circlecell/jsoncompare.com#14]
This tool is cool.

But it seems that there is some limitation about this tool:
![image](https://user-images.githubusercontent.com/6258682/63156875-489df300-c048-11e9-94ab-9bd31da354a5.png)

It's not able to sync the only  **_"a": 2_** from right side to left side, neither _**"b": 3**_ .

Could your give some explanation about how this tool works? It's base on the text comparsion or base on JSON object comparsion?

**Comment by tbaconiii** [comment]
Green on the left indicates something that was changed to the red on the right. So we see that the value 1 for a was changed to 2 and b is a new member.

**Comment by finom** [comment]
Sorry for long response. It's based on Codemirror Merge view, nothing more: https://codemirror.net/demo/merge.html
In other words it doesn't follow any JSON-specific algorithm.
