### ISSUE TITLE
Suggestion: Automatically open on specific settings

### ISSUE THREAD

**Issue by bpromasmb** [circlecell/jsoncompare.com#2]
One of my favorite things about the old JSON Lint was how immediately I could get a pretty formatted JSON. It was a quick ctrl+V and a click and voila. I know this is a very small thing, but with the new JSON Compare tool, there are a few extra steps, which for me personally, are to pick the "Beautify (tabs)" option from the settings dropdown, and click on the Fullscreen button. While the mere presence of these options is a good thing as it adds more variants to the functionalities, this breaks the flow a little bit from the previous usage of the tool.

A solution I envision for this would be to have more configurations set on the URL of the page, for instance `https://jsoncompare.com/#!/simple?settings=tabs&fullscreen=true` would open up the "simple" page on the "Beautify (tabs)" setting and on fullscreen. I could then bookmark this URL and have my own tailored quick & easy experience

**Comment by finom** [comment]
Done!
