### ISSUE TITLE
There is no way to have two or more linters open without trying to diff them

### ISSUE THREAD

**Issue by RyanMitchellWilson** [circlecell/jsoncompare.com#8]
The previous version of pro json linter had the ability to have multiple linters open at once and I can't seem to find a way to do that with the current version. The only thing I see if the diff linter but I don't want them to compare. Is there a way I can have multiple linters open on one tab without trying to diff them? There are many cases I just want to look at multiple json blobs without actually doing a diff on them.

**Comment by speckyboy** [comment]
That's a darn good point @RyanMitchellWilson, being able to add multiple linters under the 'simple' tab makes sense. Leave it with me.
