### ISSUE TITLE
Fullscreen editor cuts off final line of JSON

### ISSUE THREAD

**Issue by jamesaspence** [circlecell/jsoncompare.com#9]
![image](https://user-images.githubusercontent.com/6488043/35476856-1490038e-037d-11e8-86a0-bc7139409a9c.png)

As you can see in the above image, when in fullscreen editor mode, the sponsor bar cuts off the final line of the JSON.

**Comment by jamesaspence** [comment]
Is there a reason this was closed?

**Comment by finom** [comment]
@jamesaspence excuse me, it should be fixed now.

**Comment by jamesaspence** [comment]
Just took a look and it looks good! Thanks!

**Comment by finom** [comment]
:tada: This issue has been resolved in version 0.6.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
